### ISSUE TITLE
Demo run failed

### ISSUE THREAD

**Issue by zhentg** [HannesStark/EquiBind#16]
Dear author,

I just installed EquiBind following the tutorial, but I failed to run the demo, could you help?

python inference.py --config=configs_clean/inference.yml

```
[2022-03-09 18:32:58.749212] [ Using Seed :  1  ]
Traceback (most recent call last):
  File "inference.py", line 473, in <module>
    inference_from_files(args)
  File "inference.py", line 306, in inference_from_files
    seed_all(args.seed)
  File "/home/conda/EquiBind-main/commons/utils.py", line 62, in seed_all
    dgl.random.seed(seed)
  File "/tools/anaconda3/envs/equibind/lib/python3.7/site-packages/dgl/random.py", line 18, in seed
    _CAPI_SetSeed(val)
  File "dgl/_ffi/_cython/./function.pxi", line 287, in dgl._ffi._cy3.core.FunctionBase.__call__
  File "dgl/_ffi/_cython/./function.pxi", line 222, in dgl._ffi._cy3.core.FuncCall
  File "dgl/_ffi/_cython/./function.pxi", line 211, in dgl._ffi._cy3.core.FuncCall3
  File "dgl/_ffi/_cython/./base.pxi", line 155, in dgl._ffi._cy3.core.CALL
dgl._ffi.base.DGLError: [18:32:58] /opt/dgl/src/random/random.cc:34: Check failed: e == CURAND_STATUS_SUCCESS: CURAND Error: CURAND_STATUS_INITIALIZATION_FAILED at /opt/dgl/src/random/random.cc:34
```

Best regards
Zhenting

**Comment by HannesStark** [comment]
Hi Zhenting,

Please have a look at this issue: https://github.com/HannesStark/EquiBind/issues/4
Let me know if that is not the problem.

**Comment by zhentg** [comment]
Hi Hannes,

Thanks for redirect me to issue #4 , I did run the demo under a computer without GPU.
Now I re-submit the demo under a GPU equipped workstation, and it works.
The environment is :
CentOS 8.5, RTX 3090

Best
Zhenting
