### ISSUE TITLE
Inference should be able to be run from any directory?

### ISSUE THREAD

**Issue by jadolfbr** [HannesStark/EquiBind#34]
Running inference.py from a different project directory, gives this error.  Would it be possible to add code to allow this to be run from anywhere?  

```
Traceback (most recent call last):
  File "/home/jadolfbr/EquiBind/inference.py", line 460, in <module>
    with open(os.path.join(os.path.dirname(args.checkpoint), 'train_arguments.yaml'), 'r') as arg_file:
FileNotFoundError: [Errno 2] No such file or directory: 'runs/flexible_self_docking/train_arguments.yaml'
Traceback (most recent call last):
  File "/home/jadolfbr/EquiBind/inference.py", line 460, in <module>
    with open(os.path.join(os.path.dirname(args.checkpoint), 'train_arguments.yaml'), 'r') as arg_file:
FileNotFoundError: [Errno 2] No such file or directory: 'runs/flexible_self_docking/train_arguments.yaml'
Traceback (most recent call last):
  File "/home/jadolfbr/EquiBind/inference.py", line 460, in <module>
    with open(os.path.join(os.path.dirname(args.checkpoint), 'train_arguments.yaml'), 'r') as arg_file:
FileNotFoundError: [Errno 2] No such file or directory: 'runs/flexible_self_docking/train_arguments.yaml'
```

**Comment by jadolfbr** [comment]
Sure, I might fork and open a PR for this.  Should be fairly simple to just get the root dir and go from there.
