### ISSUE TITLE
dgl issue

### ISSUE THREAD

**Issue by mariolovric** [HannesStark/EquiBind#4]
Dear all,

I created the given environment on a windows computer and experience a dgl error.

`(equibind) PS C:\Users\reps\EquiBind> python inference.py --config=configs_clean/inference_file_for_reproduce.yml`

Using backend: pytorch
[2022-02-13 09:04:14.926225] [ Using Seed :  1  ]
Traceback (most recent call last):
  File "inference.py", line 459, in <module>
    inference(args)
  File "inference.py", line 121, in inference
    seed_all(args.seed)
  File "C:\Users\reps\EquiBind\commons\utils.py", line 62, in seed_all
    dgl.random.seed(seed)
  File "C:\Users\.conda\envs\equibind\lib\site-packages\dgl\random.py", line 18, in seed
    _CAPI_SetSeed(val)
  File "C:\Users\.conda\envs\equibind\lib\site-packages\dgl\_ffi\_ctypes\function.py", line 190, in __call__
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
  File "C:\Users\.conda\envs\equibind\lib\site-packages\dgl\_ffi\base.py", line 64, in check_call
    raise DGLError(py_str(_LIB.DGLGetLastError()))
dgl._ffi.base.DGLError: [09:04:14] C:\Users\Administrator\dgl-0.5\src\random\random.cc:34: Check failed: e == CURAND_STATUS_SUCCESS: CURAND Error: CURAND_STATUS_INITIALIZATION_FAILED at C:\Users\Administrator\dgl-0.5\src\random\random.cc:34

**Comment by HannesStark** [comment]
Hi,
Could it be that you do not have a CUDA GPU?

the env.yml installs
  - cudatoolkit=10.2
  - dgl-cuda10.2
  
 I will clarify that in the readme.

**Comment by mariolovric** [comment]
> Hi, Could it be that you do not have a CUDA GPU?
> 
> the env.yml installs
> 
> * cudatoolkit=10.2
> * dgl-cuda10.2
> 
> I will clarify that in the readme.

I did it on a windows machine to test.
Ok CUDA it is. Thanks
