### ISSUE TITLE
joblib Parallel issue with specific complex '3m1s' in the PDBBind data

### ISSUE THREAD

**Issue by luwei0917** [HannesStark/EquiBind#6]
It could be a problem with RDKit. My version is "rdkit 2021.09.4".

```
import pickle
pdbbind_dir = "PDBBind_processed/"
name = '3m1s'
lig = read_molecule(os.path.join(pdbbind_dir, name, f'{name}_ligand.sdf'), sanitize=True,
                    remove_hs=True)
if lig == None:  # read mol2 file if sdf file cannot be sanitized
    lig = read_molecule(os.path.join(pdbbind_dir, name, f'{name}_ligand.mol2'), sanitize=True,
                        remove_hs=True)
# lig = Chem.MolFromSmiles('O=C[Ru+9]12345(C6=C1C2C3=C64)n1c2ccc(O)cc2c2c3c(c4ccc[n+]5c4c21)C(=O)NC3=O')
pickle.dump(lig, open("test.pkl", "bw"))
pickle.load(open("test.pkl", "rb"))
```
RuntimeError: invalid value in pickle

**Comment by HannesStark** [comment]
Hi, thanks for the issue!
Since you are directly writing and then reading the pickle again, I am rather sure that this problem is not related to the repository.
It seems like this is rather a general issue with pickle and your concrete setup.

Let me know if I am misunderstanding something!

**Comment by HannesStark** [comment]
Understood, thanks for the clarification.
However, the get_receptor function only reads the receptor files.
Can you maybe check if the ligand that is returned by rdkit is None?

**Comment by luwei0917** [comment]
yes, I checked by adding print('hello') right after "def get_receptor(rec_path, lig, cutoff):".
it will print 'hello' as expected until it reaches "3m1s".
so I think joblib Parallel want to pickle the input.and that causes the error.

**Comment by HannesStark** [comment]
I understand, but can you maybe check with the script that you wrote above if object that is returned by the function `read_molecule` is None?

**Comment by luwei0917** [comment]
it's not None. RDkit can read the mol2 file.

**Comment by HannesStark** [comment]
Okay, then it is not a problem with RDKit and the RDKit version I think.

Could you maybe let me know the full error message?
Usually it prints more than just the final `joblib.externals.loky.process_executor._RemoteTraceback: ...
RuntimeError: invalid value in pickle`
and that information might be helpful

**Comment by luwei0917** [comment]
Sure. 
```
Get receptors: 10340it [25:17, 15.49it/s]exception calling callback for <Future at 0x7fb5adb2ca90 state=finished raised BrokenProcessPool>
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/gxr/luwei/anaconda3/envs/equibind/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 407, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "/gxr/luwei/anaconda3/envs/equibind/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
RuntimeError: invalid value in pickle
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gxr/luwei/anaconda3/envs/equibind/lib/python3.7/site-packages/joblib/externals/loky/_base.py", line 625, in _invoke_callbacks
    callback(self)
  File "/gxr/luwei/anaconda3/envs/equibind/lib/python3.7/site-packages/joblib/parallel.py", line 359, in __call__
    self.parallel.dispatch_next()
  File "/gxr/luwei/anaconda3/envs/equibind/lib/python3.7/site-packages/joblib/parallel.py", line 794, in dispatch_next
    if not self.dispatch_one_batch(self._original_iterator):
  File "/gxr/luwei/anaconda3/envs/equibind/lib/python3.7/site-packages/joblib/parallel.py", line 861, in dispatch_one_batch
    self._dispatch(tasks)
  File "/gxr/luwei/anaconda3/envs/equibind/lib/python3.7/site-packages/joblib/parallel.py", line 779, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/gxr/luwei/anaconda3/envs/equibind/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 531, in apply_async
    future = self._workers.submit(SafeFunction(func))
  File "/gxr/luwei/anaconda3/envs/equibind/lib/python3.7/site-packages/joblib/externals/loky/reusable_executor.py", line 178, in submit
    fn, *args, **kwargs)
  File "/gxr/luwei/anaconda3/envs/equibind/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 1115, in submit
    raise self._flags.broken
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.
Get receptors: 10360it [25:32, 19.78it/s]joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/gxr/luwei/anaconda3/envs/equibind/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 407, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "/gxr/luwei/anaconda3/envs/equibind/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
RuntimeError: invalid value in pickle
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train.py", line 304, in <module>
    main_function()
  File "train.py", line 295, in main_function
    train_wrapper(args)
  File "train.py", line 141, in train_wrapper
    return train(args, run_dir)
  File "train.py", line 169, in train
    train_data = PDBBind(device=device, complex_names_path=args.train_names,lig_predictions_name=args.train_predictions_name, is_train_data=True, **args.dataset_params)
  File "/gxr/luwei/packages/EquiBind/datasets/pdbbind.py", line 128, in __init__
    self.process()
  File "/gxr/luwei/packages/EquiBind/datasets/pdbbind.py", line 271, in process
    receptor_representatives = pmap_multi(get_receptor, zip(rec_paths, ligs), n_jobs=self.n_jobs, cutoff=self.chain_radius, desc='Get receptors')
  File "/gxr/luwei/packages/EquiBind/commons/utils.py", line 47, in pmap_multi
    delayed(pickleable_fn)(*d, **kwargs) for i, d in tqdm(enumerate(data),desc=desc)
  File "/gxr/luwei/anaconda3/envs/equibind/lib/python3.7/site-packages/joblib/parallel.py", line 1056, in __call__
    self.retrieve()
  File "/gxr/luwei/anaconda3/envs/equibind/lib/python3.7/site-packages/joblib/parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/gxr/luwei/anaconda3/envs/equibind/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/gxr/luwei/anaconda3/envs/equibind/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/gxr/luwei/anaconda3/envs/equibind/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/gxr/luwei/anaconda3/envs/equibind/lib/python3.7/site-packages/joblib/externals/loky/_base.py", line 625, in _invoke_callbacks
    callback(self)
  File "/gxr/luwei/anaconda3/envs/equibind/lib/python3.7/site-packages/joblib/parallel.py", line 359, in __call__
    self.parallel.dispatch_next()
  File "/gxr/luwei/anaconda3/envs/equibind/lib/python3.7/site-packages/joblib/parallel.py", line 794, in dispatch_next
    if not self.dispatch_one_batch(self._original_iterator):
  File "/gxr/luwei/anaconda3/envs/equibind/lib/python3.7/site-packages/joblib/parallel.py", line 861, in dispatch_one_batch
    self._dispatch(tasks)
  File "/gxr/luwei/anaconda3/envs/equibind/lib/python3.7/site-packages/joblib/parallel.py", line 779, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/gxr/luwei/anaconda3/envs/equibind/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 531, in apply_async
    future = self._workers.submit(SafeFunction(func))
  File "/gxr/luwei/anaconda3/envs/equibind/lib/python3.7/site-packages/joblib/externals/loky/reusable_executor.py", line 178, in submit
    fn, *args, **kwargs)
  File "/gxr/luwei/anaconda3/envs/equibind/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 1115, in submit
    raise self._flags.broken
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.
Get receptors: 10399it [31:33,  5.49it/s]
```

**Comment by HannesStark** [comment]
Sorry, I am not sure what the cause is here. One thing that would definitely work is running the get_receptor function without joblib. (Which would require rewriting the line of code)

Also, I found some posts of users circumventing similar problems by using different versions of joblib.
Can you maybe try:
`conda install -c anaconda joblib=1.1.0`
`conda install -c anaconda joblib=1.2.0`

**Comment by gaozhangyang** [comment]
Thanks for the wonderful work!

I solved the problem by replacing following codes in `process_mol.py`:

`coords = lig.GetConformer().GetPositions()==>coords = get_rdkit_coords(lig).numpy()`

and removing some training complexes:

`3zs1
3p3h
4jfv
4acu
3w8o
4mdn
2jld
3m1s
3p3j
4jfw
5tgy
4dcy
3p44
4i60
4jhq`

and validation complexes:

`4xkc
3p55
3rj7`

**Comment by HannesStark** [comment]
Great to hear!
Thanks for the information that some versions have issues with the ligands in the mentioned complexes.
