### ISSUE TITLE
Keep getting the OSError 

### ISSUE THREAD

**Issue by Nailo** [HannesStark/EquiBind#62]
I tried to reproduce the training, I extracted the PDBBind folder and put it in the data folder.
And use the command "python train.py --config=configs_clean/RDkitCoords_flexible_self_docking.yml"
Then I get the errors listed below：

Traceback (most recent call last):
  File "train.py", line 304, in <module>
    main_function()
  File "train.py", line 295, in main_function
    train_wrapper(args)
  File "train.py", line 141, in train_wrapper
    return train(args, run_dir)
  File "train.py", line 169, in train
    train_data = PDBBind(device=device, complex_names_path=args.train_names,lig_predictions_name=args.train_predictions_name, is_train_data=True, **args.dataset_params)
  File "C:\Users\Equibind\datasets\pdbbind.py", line 127, in __init__
    self.process()
  File "C:\Users\Equibind\datasets\pdbbind.py", line 227, in process
    remove_hs=self.remove_h)
  File "C:\Users\Equibind\commons\process_mols.py", line 1223, in read_molecule
    supplier = Chem.SDMolSupplier(molecule_file, sanitize=False, removeHs=False)
OSError: File error: Bad input file data/PDBBind\3dpf\3dpf_ligand.sdf

**Comment by vedantg-1311** [comment]
how did you solve the problem?
