### ISSUE TITLE
pyaml syntax error

### ISSUE THREAD

**Issue by BlackWyvernX** [HannesStark/EquiBind#71]
(equibind) akshat@Akshat:/mnt/d/program/condaenv/equibind$ python inference.py --config=configs_clean/inference.yml
Traceback (most recent call last):
  File "inference.py", line 21, in <module>
    from train import load_model
  File "/mnt/d/program/condaenv/equibind/train.py", line 13, in <module>
    from trainer.binding_trainer import BindingTrainer
  File "/mnt/d/program/condaenv/equibind/trainer/binding_trainer.py", line 4, in <module>
    from trainer.trainer import Trainer
  File "/mnt/d/program/condaenv/equibind/trainer/trainer.py", line 7, in <module>
    import pyaml
  File "/home/akshat/miniconda3/envs/equibind/lib/python3.7/site-packages/pyaml/__init__.py", line 14
    if (sort_keys := kws.pop('sort_dicts', None)) is not None:
                  ^
SyntaxError: invalid syntax

this is the error I am getting again and again

**Comment by DanLep97** [comment]
I am getting the same issue.
